# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 497ccdde7e46a1844ad5b552ab59312afc0240e4eb063c4dc77278ff885b31b5739c258e17c79c5ad907f1fa3ee51ed4ec241341ba55ca4f8f7b60381d17ae5b

test:
  secret_key_base: 0f8aef6b34e43c9ec8d52c82a9f73110fcc52067b95325ac9156b4685ac0a5f5765c97d10d0ffe33f708804c946390ad7fe7ea6568012a258981d6b2215aa12e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
